### ISSUE TITLE
Drop citation cache in meta service upon DOI metadata save

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/doi#16]
At the moment, meta service caches the citations fetched from DOI indefinitely, until a call is made to a dedicated API, instructing it to drop citation cache for a particular DOI. doi editing app should make that call when metadata has been saved.

**Comment by klarakristina** [comment]
Fixed in [https://github.com/ICOS-Carbon-Portal/doi/pull/17](url)
